[package]
name = "rlox"
version = "0.1.0"
authors = ["Jorge Luis PÃ©rez <jorge.perez@almundo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
